from typing import overload
from .QtCore import QEvent, QCoreApplication, QObject

class QKeySequence(int):

    Quit: QKeySequence

class QCloseEvent(QEvent): ...

class QPaintDevice: ...

class QPixmap(QPaintDevice):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    @overload
    def __init__(self, fileName: str, format: str = ..., flags: Qt.ImageConversionFlag = ...) -> None: ...
    @overload
    def __init__(self, xpm: str) -> None: ...
    @overload
    def __init__(self, pixmap: QPixmap) -> None: ...

class QIconEngine: ...

class QIcon:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pixmap: QPixmap) -> None: ...
    @overload
    def __init__(self, other: QIcon) -> None: ...
    @overload
    def __init__(self, fileName: str) -> None: ...
    @overload
    def __init__(self, engine: QIconEngine) -> None: ...

class QGuiApplication(QCoreApplication): ...

class QTextDocument(QObject):
    def setDefaultStyleSheet(self, sheet: str) -> None: ...
    def defaultStyleSheet(self) -> str: ...
